### ISSUE TITLE
Custom Error Messages settings don't show up

### ISSUE THREAD

**Issue by jstnrs** [Domaneni/custom-error-messages-for-gravityforms#7]
Hello @Domaneni,

I've installed your plugin on WordPress 6.0 with Gravity Forms 2.7.10.1. I can activate the plugin, but can't find where the settings fields are in WP Admin to customize the error messages. Where can I find the fields, or is something not working in my setup after activating the plugin?

Thanks in advance.

**Comment by Domaneni** [comment]
Hi,
I just noticed, that I am really bad with description. You need to go to Field Settings -> Advanced and there you find Allow custom error messages. Please let me know if it is there and I will update the plugin description

![image](https://github.com/Domaneni/custom-error-messages-for-gravityforms/assets/4079453/b69cafca-a69a-4fa3-bd65-74d74aba7394)

**Comment by jstnrs** [comment]
Thanks for your quick reply! I though the custom messages were globally for all forms, but found these, thanks!

**Comment by Domaneni** [comment]
> Thanks for your quick reply! I though the custom messages were globally for all forms, but found these, thanks!

Custom messages works for each field separately. I didn't want to add any other options page when the Field settings are fine. Or do you suggest any changes?

**Comment by jstnrs** [comment]
By default the messages are nog translated in different languages. Adding this to the global options/settings for forms would make it quick to translate the default validation messages.

**Comment by Domaneni** [comment]
So you would like to have default validation messages that you will be able to set for the whole form and it will be used if the field one is not filled?

That means you can have Default required message: This field is required. And then for email you can override it with: Please fill your email.

**Comment by jstnrs** [comment]
I think it would be useful, it would be an easy way to customize messages.

**Comment by Domaneni** [comment]
> I think it would be useful, it would be an easy way to customize messages.

Ok I will try to implement it

**Comment by Domaneni** [comment]
Default error message settings were added in version 1.0.5
